baseURL = "http://example.org/"
languageCode = "en-us"
title = "PointyFar"
theme = "pointyblog"
themesDir = "../pointyfar-themes/"
# contentDir = "content-food"

pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true

sectionPagesMenu = "main"

# disqusShortname = "disqusShortname"

[[menu.main]]
    name = "Blog"
    title = "Blog Section"
    weight = 120
    identifier = "post"
    url = "/post/"

[[menu.main]]
    name = "Tags"
    title = "Tags List"
    weight = 130
    identifier = "tags"
    url = "/tags/"
    
    
[params]
  subtitle = "Adventures in Hugoland"
  copyright = "Copyright © 2018"
  author = "Pointy Far"
  brand = "Pointy's"
  heroImage = "stock/beach.jpeg"
  
  footerNotice = "Powered by Hugo. Themed by PointyFar"

  mainSections = ["post", "test"]
  bundleCss = "/bundle.css"
  bundleJs = "/bundle.js"

[params.map]
  enabled = true
  mapimg = "food/map.jpeg"
  lat = 37.4220041
  long = -122.0862515

[[params.legal]]
  legalurl = "#"
  legaltext = "Legal Notice 1"

[[params.legal]]
  legalurl = "#"
  legaltext = "Legal Notice 2"
  
[[params.legal]]
  legalurl = "#"
  legaltext = "Legal Notice 3"

[[params.social]]
  url = "http://www.twitter.com"
  icon = "fab fa-twitter"
  color = "#55acee"

[[params.social]]
  url = "http://www.github.com"
  icon = "fab fa-github"
  color = "#000000"
